### ISSUE TITLE
404 and 401 errors on some objects

### ISSUE THREAD

**Issue by ccheek21** [newrelic/nri-rabbitmq#21]
##### Description of the problem

Aliveness tests and health checks sometimes fail. May be related to invalid URL encoding. More info attached.

[zd333331-nri-rabbitmq.tar.gz](https://github.com/newrelic/nri-rabbitmq/files/2784263/zd333331-nri-rabbitmq.tar.gz)

##### OS

- [x] All of them
- [ ] Amazon Linux, all versions
- [ ] CentOS, version 6 or higher
- [ ] Debian, version 7 ("Wheezy") or higher
- [ ] Red Hat Enterprise Linux (RHEL), version 6 or higher
- [ ] Ubuntu, versions 12.04, 14.04, and 16.04 (LTS  versions)
- [ ] Windows Server, 2008 and 2012 and their service packs

**Comment by ccheek21** [comment]
Waiting on an environment

**Comment by ccheek21** [comment]
Cannot reproduce, and no response from customer

**Comment by kfalconer** [comment]
I am seeing this same issue using latest version of nri-rabbitmq.

Here are relevant logs:

````
time="2019-06-19T15:22:39-04:00" level=debug msg="using environment [VHOSTS=[\"jvdjvrsd\"] HOSTNAME=<hostname>.com PORT=15672 USERNAME=<username> PASSWORD=<password> PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin VERBOSE=1 USE_SSL=false]" data prefix=integration/com.newrelic.rabbitmq plugin name=funny-swan
time="2019-06-19T15:22:39-04:00" level=debug msg="plugin returned no output" data prefix=integration/com.newrelic.rabbitmq plugin name=funny-swan
time="2019-06-19T15:22:39-04:00" level=debug msg="executing data source" data prefix=integration/com.newrelic.rabbitmq plugin name=funny-swan stderr="15:22:39.856319 [DEBUG] store file (/tmp/nr-integrations/com.newrelic.rabbitmq.json) is older than 1m0s, skipping loading from disk.\n[ERR] Error making API call: unexpected http response from [http://<hostname>:15672/api/aliveness-test/%2F]: 401 Unauthorized\n[DEBUG] Skipping entity with name: /, entity type: vhost, vhost: /\n"
````
From the output the plugin believes that the configured vhost is `/`, but in configuration below you can see that an explict name has been given:

````yaml
integration_name: com.newrelic.rabbitmq

instances:
  - name: funny-swan
    command: "events"
    arguments:
      hostname: <hostname>
      port: 15672
      username: <username>
      password: <password>
      use_ssl: false
      vhosts: '["jvdjvrsd"]'
    labels:
      env: production
      role: rabbitmq
````
