### ISSUE TITLE
CPU usage keeps growing in windows 2012R2 VM

### ISSUE THREAD

**Issue by pranaslu** [newrelic/nri-rabbitmq#71]
## Description
CPU usage keeps growing when RabbitMQ integration is added to agent on Windows 2012R2 VM. It starts with ~5%CPU consumption after agent restart, and after a day it's consuming 30% and keeps growing.
![image](https://user-images.githubusercontent.com/24253081/120611584-0338f880-c45d-11eb-977f-0adb9b5b4add.png)

Memory is growing as well:
![image](https://user-images.githubusercontent.com/24253081/120612258-b275cf80-c45d-11eb-9889-92d2c3bd5989.png)

## Expected Behavior
CPU usage should be stable

## [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce
Follow installation instruction with default settings

## Your Environment
Windows 2012R2 VM
RabbitMQ 3.7.5 Erlang 20.3

## Additional context

rabbitmq-win-definition.yml

```
name: com.newrelic.rabbitmq
description: Reports status and metrics for rabbitmq service
protocol_version: 2
os: windows

commands:
  all:
    command:
      - .\bin\nri-rabbitmq.exe
    prefix: config/rabbitmq
    interval: 60

  inventory:
    command:
      - .\bin\nri-rabbitmq.exe
      - -inventory
    prefix: config/rabbitmq
    interval: 60
  
  events:
    command:
      - .\bin\nri-rabbitmq.exe
      - -events
    interval: 60
```

rabbitmq-config.yml

```
integration_name: com.newrelic.rabbitmq

instances:
  - name: rabbit@........maskedclustername
    command: all
    arguments:
      hostname: localhost
      port: 15672
      username: ...masked
      password: ...masked
      config_path: 
    labels:
      env: production
      role: rabbitmq
````
